apiVersion: apps/v1
kind: Deployment
metadata:
  name: @project.name@-deployment
  labels:
    app: @project.name@
spec:
  selector:
    matchLabels:
      app: @project.name@
  replicas: 2
  template:
    metadata:
      labels:
        app: @project.name@
    spec:
      containers:
        - name: ${project.name}
          image: cedcori/${project.name}
          ports:
            - containerPort: ${server.port}