apiVersion: v1
kind: Service
metadata:
  name: ${project.name}-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: ${server.port}
  selector:
    app: ${project.name}
  type: NodePort